name: nhathuoc_mobilee
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.2
  app_links: ^6.3.0
  flutter_dotenv: ^5.0.4
  webview_flutter: ^4.13.0
  provider: ^6.1.2
  collection: ^1.19.0
  get_it: ^9.1.1
  flutter_secure_storage: ^9.2.4
  shimmer: ^2.0.0
  dtd: ^4.0.0
  flutter_lints: ^6.0.0
  google_fonts: ^6.3.3
  json_rpc_2: ^4.0.0
  path: ^1.9.1
  stack_trace: ^1.12.1
  web: ^1.1.1
  speech_to_text: ^7.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/